version: '3.9'

services:
    app:
        build:
            context: .docker/php
            dockerfile: Dockerfile
        image: your-app-name/laravel-app
        container_name: laravel-app
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:80"
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=http://localhost:9000
            - LOG_CHANNEL=stack
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=sail
            - DB_PASSWORD=password
        depends_on:
            - db
            - web

    web:
        build:
            context: ./docker/web
            dockerfile: Dockerfile
        image: your-app-name/nginx
        container_name: webserver
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: postgres:latest
        container_name: database
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: sail
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
