version: '3.9'

services:
    app:
        build:
            context: .docker/development/php
            dockerfile: Dockerfile
        container_name: pupsched-app
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
            # - "5173:5173"
        networks:
            - pupsched-network
        depends_on:
            - postgresql
        env_file:
            - .env

    node:
        build:
            context: .docker/development/node
            dockerfile: Dockerfile
        container_name: pupsched-node
        volumes:
            - ./:/app
        tty: true
        ports:
            - "5173:5173"
        networks:
            - pupsched-network

    postgresql:
        image: postgres:latest
        container_name: pupsched-postgresql
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - pupsched-network

    # nginx:
    #     image: nginx:latest
    #     container_name: pupsched-nginx
    #     ports:
    #         - "8080:80"
    #     volumes:
    #         - ./:/var/www/pupsched
    #         - .docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #     networks:
    #         - pupsched-network
    #     depends_on:
    #         - app
volumes:
    pgdata:

networks:
    pupsched-network:
        driver: bridge

